# helper to run Cal.com locally — local Postgres for prisma
services:
  postgres:
    image: postgres:15
    ports:
      - "5450:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "calendso"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calendso"]
      interval: 10s
      timeout: 5s
      retries: 5
  # postgres_is_ready:
  #   image: postgres:15
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
volumes:
  db_data:
